{"uid":"e6d23a244152d47c","name":"Нельзя создать двух одинаковых курьеров","fullName":"tests.test_create_courier.TestCreateCourier#test_create_duplicate_courier","historyId":"b0188f64bd1dcf0f2ef38757ee9d9fab","time":{"start":1746684024035,"stop":1746684024232,"duration":197},"status":"failed","statusMessage":"AssertionError: Ожидалось сообщение 'Этот логин уже используется', получено 'Этот логин уже используется. Попробуйте другой.'\nassert 'Этот логин уже используется' == 'Этот логин у...буйте другой.'\n  \n  - Этот логин уже используется. Попробуйте другой.\n  + Этот логин уже используется","statusTrace":"self = <test_create_courier.TestCreateCourier object at 0x0000020CD57AA710>\ncourier = ({'firstName': 'qkcobrwcjy', 'login': 'wmfhbkpban', 'password': 'bporahgtgu'}, <Response [201]>)\n\n    @allure.title(\"Нельзя создать двух одинаковых курьеров\")\n    def test_create_duplicate_courier(self, courier):\n        courier_data, response = courier\n        duplicate_response = CourierApi.create(courier_data)\n        assert duplicate_response.status_code == 409, \\\n            f\"Ожидался статус 409, получен {duplicate_response.status_code}\"\n        expected_message = Constants.DUPLICATE_LOGIN\n        actual_message = duplicate_response.json().get(\"message\", \"\")\n>       assert expected_message == actual_message, \\\n            f\"Ожидалось сообщение '{expected_message}', получено '{actual_message}'\"\nE       AssertionError: Ожидалось сообщение 'Этот логин уже используется', получено 'Этот логин уже используется. Попробуйте другой.'\nE       assert 'Этот логин уже используется' == 'Этот логин у...буйте другой.'\nE         \nE         - Этот логин уже используется. Попробуйте другой.\nE         + Этот логин уже используется\n\ntests\\test_create_courier.py:22: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[{"name":"courier","time":{"start":1746684023882,"stop":1746684024034,"duration":152},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false,"hasContent":false}],"afterStages":[{"name":"courier::0","time":{"start":1746684024388,"stop":1746684024728,"duration":340},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"attachmentStep":false,"hasContent":false}],"labels":[{"name":"story","value":"Создание курьера"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_create_courier"},{"name":"subSuite","value":"TestCreateCourier"},{"name":"host","value":"sis-admin2025"},{"name":"thread","value":"11284-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_create_courier"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"3e6f7634469e920","status":"failed","statusDetails":"AssertionError: Ожидалось сообщение 'Этот логин уже используется', получено 'Этот логин уже используется. Попробуйте другой.'\nassert 'Этот логин уже используется' == 'Этот логин у...буйте другой.'\n  \n  - Этот логин уже используется. Попробуйте другой.\n  + Этот логин уже используется","time":{"start":1746619271782,"stop":1746619271980,"duration":198}}],"categories":[{"name":"Product defects","matchedStatuses":[]}],"tags":[]},"source":"e6d23a244152d47c.json","parameterValues":[]}